export const CREATE_SHARED_LIST = 'CREATE_SHARED_LIST'
export const JOINED_SHARED_LIST = 'JOINED_SHARED_LIST'
export const JOIN_ROOM = 'JOIN_ROOM'

export const CREATE_NEW_LIST = 'CREATE_NEW_LIST';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_LISTS_UPDATE = 'USER_LISTS_UPDATE';
export const USER_LIST_DELETE = 'USER_LIST_DELETE';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const ADD_TODO_OBJECT = 'ADD_TODO_OBJECT';
export const UPDATE_DISPLAYED_TODOS = 'UPDATE_DISPLAYED_TODOS';