export const CREATE_SHARED_LIST:string = 'CREATE_SHARED_LIST'
export const JOINED_SHARED_LIST:string = 'JOINED_SHARED_LIST'

export const CREATE_NEW_LIST = 'CREATE_NEW_LIST';
export const USER_LISTS_UPDATE = 'USER_LISTS_UPDATE';
export const USER_LIST_DELETE = 'USER_LIST_DELETE';